### ISSUE TITLE
Actually, `serde_with` has the ability to delegate to a `FromStr` impl, so we can have both. `derive_more` should be able to auto-generate the `FromStr` implementations.

### ISSUE THREAD

**Issue by appetrosyan** [soramitsu/iroha2-longevity-load-rs#41]
Actually, `serde_with` has the ability to delegate to a `FromStr` impl, so we can have both. `derive_more` should be able to auto-generate the `FromStr` implementations.

_Originally posted by @appetrosyan in https://github.com/soramitsu/iroha2-longevity-load-rs/pull/35#discussion_r1002944785_

**Comment by pesterev** [comment]
I've used `strum` [here](https://github.com/soramitsu/iroha2-longevity-load-rs/pull/35). The reason to use `strum` instead of `derive_more` is that `derive_more` [doesn't support](https://jeltef.github.io/derive_more/derive_more/from_str.html#enums) auto-gen `FromStr` for enumerations.

So we can close this issue.
